# -*- coding: utf-8 -*-
"""Deep learning project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SELs9w-RRUzawqV12R3TN5gCEoxko7PZ
"""

import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Flatten

(X_train, y_train), (X_test, y_test) = keras.datasets.mnist.load_data()

X_train.shape
(60000, 28, 28)

y_test

import matplotlib.pyplot as plt
plt.imshow(X_train[1])

X_train = X_train/255
X_test = X_test/255

X_train[0]



model = Sequential()
model.add(Flatten(input_shape=(28,28)))
model.add(Dense(128, activation='relu'))
model.add(Dense(10, activation='softmax'))

model.summary()
Model: "sequential_1"

model.compile(loss='sparse_categorical_crossentropy',optimizer='Adam')

model.fit(X_train, y_train, epochs=10, validation_split=0.2)

y_prob = model.predict(X_test)

y_pred = y_prob.argmax(axis=1)

from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

